name: Black Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  black_check:
    name: "Check Black Formatting"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        export PATH="/opt/hostedtoolcache/Python/3.9.15/x64/lib/sgengine:$PATH"
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install -r requirements-ci.txt

    - name: Check Black Formatting
      run: |
        python3 -m black --check ./sgengine
