name: Black Format

on: [push,pull_request]
jobs:
  black_check:
    name: "Check Black Formatting"

    runs-on: ubuntu-latest
    container: osrf/ros:humble-desktop

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Git Submodule Update
      run: |
        git config --global safe.directory '*'
        git pull --recurse-submodules
        git submodule update --remote --recursive
    - name: Install Python
      run: |
        apt-get update
    - name: Install dependencies
      run: |
        ./scripts/install_deps.py

    - name: Check Black Formatting
      run: |
        python3 -m black --check ./sgengine/sgengine
    - name: Lint with pylint
      shell: bash
      run: |
        # Source ROS
        source /opt/ros/humble/setup.bash

        python3 -m pylint ./sgengine/sgengine --rcfile=.pylint
    - name: Lint with flake8
      run: |
        python3 -m flake8 ./sgengine/sgengine --config .flake8
