name: Flake8

on: [push,pull_request]
jobs:
  flake8_check:
    name: "Flake8 Format Checking"

    runs-on: ubuntu-latest
    container: osrf/ros:humble-desktop

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive
    - name: Install Python
      run: |
        apt-get update
    - name: Install dependencies
      run: |
        ./scripts/installDeps.sh

    - name: Lint with flake8
      run: |
        # stop the build if there are...
        # Python syntax errors or undefined names
        # Unused imports
        # No new line
        # No whitespace after keyword


        # Ignore...
        # Whitespace in new line
        # Trailing whitespace
        # Too many blank lines
        # Whitespace before :, Line break occurred before a binary operator (Black breaks this)

        python3 -m flake8 --exclude=sgengine/sgengine/hardware/utils --exclude=sgengine/sgengine/aruco ./sgengine/sgengine --count --select=E9,F63,F7,F82,F401,W292,E275,F403 --extend-ignore=W293,W291,E303,E203,W503 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        python3 -m flake8 --exclude=sgengine/sgengine/hardware/utils --exclude=sgengine/sgengine/aruco ./sgengine/sgengine --count --exit-zero --max-complexity=10 --max-line-length=140 --extend-ignore=E203 --statistics
        