name: PyLint

on: [push,pull_request]
jobs:
  pylint_check:
    name: "PyLint check"

    runs-on: ubuntu-latest
    container: osrf/ros:humble-desktop

    steps:
    - uses: actions/checkout@v1
    - name: Install Python
      run: |
        apt-get update
    - name: Install dependencies
      run: |
        export PATH="/opt/hostedtoolcache/Python/3.9.15/x64/lib/sgengine:$PATH"
        git submodule update --init --recursive
        ./scripts/installDeps.sh

    - name: Lint with pylint
      shell: bash
      run: |
        # Source ROS
        source /opt/ros/humble/setup.bash

        # Ignore...
        # Wildcard import,
        # Trailing whitespace
        # Missing module docstring
        # Too many instance attributes
        # Too many public methods
        # Multiple trailing newlines
        # Too broad of an exception
        # consider-using-enumerate
        # Too many arguments
        # Too many local variables
        # Unnecessary pass statement
        # Logging fstring interpolation
        # Useless parent or super() delegation 

        python3 -m pylint ./sgengine/sgengine --ignore-paths=sgengine/sgengine/hardware/utils --ignore-paths=sgengine/sgengine/aruco --disable=C0303,C0114,W0401,R0902,R0904,C0305,W0703,C0200,R0913,R0914,W0107,W1203,W0246,W0511,R0801
        