name: PyLint

on: [push,pull_request]

jobs:
  pylint_check:
    name: "PyLint check"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        export PATH="/opt/hostedtoolcache/Python/3.9.15/x64/lib/sgengine:$PATH"
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install -r requirements-ci.txt

    - name: Lint with pylint
      run: |
        # Ignore...
        # Wildcard import,
        # Trailing whitespace
        # Missing module docstring
        # Too many instance attributes
        # Too many public methods
        # Multiple trailing newlines
        # Too broad of an exception
        # consider-using-enumerate
        # Too many arguments
        # Too many local variables
        # Unnecessary pass statement
        # Logging fstring interpolation
        # Useless parent or super() delegation 

        python3 -m pylint ./sgengine --disable=C0303,C0114,W0401,R0902,R0904,C0305,W0703,C0200,R0913,R0914,W0107,W1203,W0246,W0511
        